---
- name: Setup webserver
  hosts: webserver
  become: yes

  tasks:
    - name: Run apt update and upgrade
      apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 432000

    - name: Install Apache2
      apt:
        name: apache2
        state: latest
        update_cache: yes

    - name: Install php prerequisites
      apt:
        pkg:
          - ca-certificates
          - apt-transport-https
          - software-properties-common
          - lsb-release
          - gnupg2
          - gnupg
          - curl
          - wget
        update_cache: yes

    - name: Get APT Key
      shell:
        cmd: wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg

    - name: Get APT keyring
      shell:
        cmd: sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'

    - name: Apt update
      apt:
        update_cache: true
        upgrade: true

    - name: Install php8.1
      apt:
        name: php8.1-fpm
        state: latest
        update_cache: yes

    - name: Install fcgid
      apt:
        name: libapache2-mod-fcgid
        state: latest
        update_cache: yes

    - name: Enable PHP FPM
      shell: |
        a2enmod proxy_fcgi setenvif
        a2enconf php8.1-fpm
      become: yes

    - name: Restart apache
      service:
        name: apache2
        state: restarted
      become: yes

    - name: Get stats of index.html
      stat:
        path: /var/www/html/index.html
      register: index

    - name: Move index.html to index.php if it exists
      command: mv /var/www/html/index.html /var/www/html/index.php
      when: index.stat.exists

    - name: Copy index.php
      copy:
        src: mytemplates/index.php
        dest: /var/www/html/index.php
      become: yes

    - name: Restart apache
      service:
        name: apache2
        state: restarted
      become: yes
